config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  mount ActionCable.server => '/cable'

  resource :home, only: [:index]
  resources :rooms, only: [:new, :create, :show, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    gon.current_user = current_user
    @rooms = Room.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, :assign_current_user_gon

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    flash[:error] = "Cannot create a new room." unless @room.save
    redirect_to root_path
  end

  def show
    gon.room_id = params[:id]
  end

  def destroy
  end

  private

  def assign_current_user_gon
    gon.current_user = current_user
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
Hello <%= current_user.try(:email) %> !

Select room or create new:

<table class="table">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Users count</th>
    <th>Join link</th>
  </tr>

  <% @rooms.each do |room| %>
    <tr>
      <td><%= room.id %></td>
      <td><%= room.name %></td>
      <td><%= room.users.count %></td>
      <td><%= link_to 'Join', room %></td>
    </tr>
  <% end %>
</table>

<br>
<br>
<%= link_to 'Create a new one!', new_room_path, class: "btn btn-primary" %>

app/views/layouts/_react_hot_assets.html.erb
<% if Rails.env.development? %>
  <script src='http://localhost:8080/assets/react_bundle.js'></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reactapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= action_cable_meta_tag %>
  <%= csrf_meta_tags %>
  <%= include_gon %>
</head>
<body>
<%= render 'layouts/react_hot_assets' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/rooms/new.html.erb
<h2>Create a new room</h2>

<%= form_for @room do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit "Save" %>
<% end %>

app/views/rooms/show.html.erb
<%= react_component 'ReduxContainer' %>